{
  "RHSA-2019:3590": {
    "auditts": 1573681647,
    "comparisons": {
      "8-bucket": {
        "comparison-collection-subtype": [
          "python3-urllib3"
        ],
        "comparison-collection-type": [
          "packages"
        ],
        "comparison-match": "aptge",
        "comparison-match-value": [
          "1.24.2"
        ]
      }
    },
    "filters": {
      "8-bucket": {
        "filter-collection-subtype": [
          "default",
          "default"
        ],
        "filter-collection-type": [
          "os_family",
          "os_release"
        ],
        "filter-match": "is",
        "filter-match-value": [
          "RedHat",
          8
        ]
      }
    },
    "jellyfishversion": "2.6",
    "vuln-additional-links": {
      "CVE-2019-11236": "https://access.redhat.com/security/cve/CVE-2019-11236",
      "CVE-2019-11324": "https://access.redhat.com/security/cve/CVE-2019-11324",
      "bz#1700824: CVE-2019-11236 python-urllib3: CRLF injection due to not encoding the '\\r\\n' sequence leading to possible attack on internal service": "https://bugzilla.redhat.com/show_bug.cgi?id=1700824",
      "bz#1702473: CVE-2019-11324 python-urllib3: Certification mishandle when error should be thrown": "https://bugzilla.redhat.com/show_bug.cgi?id=1702473",
      "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.1_release_notes/": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.1_release_notes/",
      "https://access.redhat.com/errata/RHSA-2019:3590": "https://access.redhat.com/errata/RHSA-2019:3590",
      "https://access.redhat.com/security/updates/classification/#moderate": "https://access.redhat.com/security/updates/classification/#moderate",
      "https://www.openwall.com/lists/oss-security/2019/04/17/3": "https://www.openwall.com/lists/oss-security/2019/04/17/3"
    },
    "vuln-long-description": "An update for python-urllib3 is now available for Red Hat Enterprise Linux 8.\nRed Hat Product Security has rated this update as having a security impact of Moderate. A Common Vulnerability Scoring System (CVSS) base score, which gives a detailed severity rating, is available for each vulnerability from the CVE link(s) in the References section.\n\nThe python-urllib3 package provides the Python HTTP module with connection pooling and file POST abilities.\nSecurity Fix(es):\n* python-urllib3: CRLF injection due to not encoding the '\\r\\n' sequence leading to possible attack on internal service (CVE-2019-11236)\n* python-urllib3: Certification mishandle when error should be thrown (CVE-2019-11324)\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.\nAdditional Changes:\nFor detailed information on changes in this release, see the Red Hat Enterprise Linux 8.1 Release Notes linked from the References section.\n\nPlease see https://www.redhat.com/footer/terms-of-use.html",
    "vuln-name": "RHSA-2019:3590",
    "vuln-primary-link": "https://access.redhat.com/errata/RHSA-2019:3590",
    "vuln-priority": 1,
    "vuln-short-description": "An update for python-urllib3 is now available for Red Hat Enterprise Linux 8.\nRed Hat Product Security has rated this update as having a security impact of Moderate. A Common Vulnerability Scoring System (CVSS) base score, which gives a detailed severity rating, is available for each vulnerability from the CVE link(s) in the References section."
  }
}